server.port=8080
spring.thymeleaf.cache=false

# DBSET/EIMS_DBSET で作成するデータベースに接続します。
spring.datasource.url=jdbc:mysql://localhost/eimsdb?serverTimezone=Asia/Tokyo
spring.datasource.username=eimsuser
spring.datasource.password=Pa$$w0rd

# アプリ起動時に、EntityとDBのテーブル定義が一致しているかを検証します。
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
