server.port=8080
spring.thymeleaf.cache=false

# DBSET/EIMS_DBSET で作成するデータベースに接続します。
spring.datasource.url=jdbc:mysql://localhost/eimsdb?serverTimezone=Asia/Tokyo
spring.datasource.username=eimsuser
spring.datasource.password=Pa$$w0rd

# 演習中にEntityを追加したとき、Hibernateがテーブル定義を更新できるようにします。
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
